### ISSUE TITLE
ESP32 specific language spec missing

### ISSUE THREAD

**Issue by Ebiroll** [tslater2006/esp32_flash_loader#4]
Hello, Where is it possible to find the ESP32 specific language spec?
I like the esp32_rom.elf loading but cannot find the ESP32 specific spec for ghidra.

**Comment by Ebiroll** [comment]
Also I did a small story on medium. https://medium.com/@olof.astrand/enter-home-dragon-with-ghidra-3ed7ddf75935 Any thoughts about this?

**Comment by tslater2006** [comment]
I'm currently using the language spec by hedgeberg on GitHub. It has
support for the rolling window feature.

**Comment by Ebiroll** [comment]
Thanks. Did you manage to load the rom.elf file after importing the flash file?

**Comment by tslater2006** [comment]
Yep! My latest loader should do that is the esp32_rom.elf is in the data
directory. Not sure if I've pushed the change or not. Need to do some major
cleanup tomorrow and then I'll go thru the PRs for the esp32s support.
Thanks for those.

**Comment by Ebiroll** [comment]
Yes. It works. I just did not know it had to go to the data directory.
Unfortunately, not so many calls goes directly to the rom on the esp32.

**Comment by tslater2006** [comment]
Depends on the application. It's nice to be able to see malloc calls and
such which are in the rom.
